services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    depends_on:
      - database
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm run start:dev"
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
    env_file:
      - ./webapp/.env
    depends_on:
      - api
    command: sh -c "npm ci; npm run dev"

  database:
    container_name: tasks_db
    image: postgres:15
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: